spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://postgres:3ZUKzMb4LDk9vjU8r0oU$containers-us-west-107.railway.app:6117/railway
    username: postgres
    password: 3ZUKzMb4LDk9vjU8r0oU
    driverClassName: org.postgresql.Driver